"""Add transaction_date column

Revision ID: d972e5929351
Revises: eca771c81dc5
Create Date: 2024-02-21 18:28:09.082656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd972e5929351'
down_revision: Union[str, None] = 'eca771c81dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('transactions', sa.Column('transaction_date', sa.Date(), nullable=False,  server_default="2023-01-01"))
    #op.alter_column('transactions', 'transaction_type',
               #existing_type=sa.VARCHAR(length=50),
               #type_=sa.Enum('income', 'expense', name='transaction_types'),
               #nullable=False)#
    #op.drop_column('transactions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('transactions', sa.Column('date', sa.DATE(), server_default=sa.text("'2023-01-01'"), nullable=False))
    #op.alter_column('transactions', 'transaction_type',
               #existing_type=sa.Enum('income', 'expense', name='transaction_types'),
               #type_=sa.VARCHAR(length=50),
               #nullable=True)
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
