"""Add date to transactions

Revision ID: eca771c81dc5
Revises: 96085aad7e49
Create Date: 2024-02-21 06:45:39.001173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca771c81dc5'
down_revision: Union[str, None] = '96085aad7e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('transactions', sa.Column('date', sa.Date(), nullable=False, server_default=sa.text("'2023-01-01'")))
    #transaction_type_enum = sa.Enum('income', 'expense', name='transaction_types', create_type=False)
    #op.alter_column('transactions', 'transaction_type', type_=transaction_type_enum, 
                        #existing_type=sa.VARCHAR(length=50), nullable=False, existing_nullable=False)#
    # ### end Alembic commands ###


 def downgrade():
    op.alter_column('transactions', 'transaction_type',
                    existing_type=sa.Enum('income', 'expense', name='transaction_types'),
                    type_=sa.VARCHAR(length=50),
                    nullable=True)
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
